# Generated by Django 2.0.5 on 2018-05-22 17:43

import astroApp.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', djongo.models.fields.EmbeddedModelField(model_container=astroApp.models.BlogContent, null=True)),
                ('headline', models.CharField(max_length=255)),
            ],
        ),
    ]
