# Generated by Django 2.0.5 on 2018-05-22 19:18

import astroApp.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('astroApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', djongo.models.fields.EmbeddedModelField(model_container=astroApp.models.ParamsContent, null=True)),
            ],
        ),
    ]
